- id: office_off
  alias: Office off
  trigger:
  - entity_id: device_tracker.garret_phone
    event: leave
    platform: zone
    zone: zone.home
  action:
  - data:
      entity_id: group.garret_office
    service: homeassistant.turn_off
- id: office_on
  alias: Office on
  trigger:
  - entity_id: device_tracker.garret_phone
    event: enter
    platform: zone
    zone: zone.home
  action:
  - data:
      entity_id: group.garret_office
    service: light.turn_on
- id: living_room_lights_sunset
  alias: Living room on before sunset
  trigger:
  - event: sunset
    offset: -01:00:00
    platform: sun
  action:
  - data:
      transition: 60
    entity_id: group.living_room
    service: light.turn_on
- id: living_room_lights_night
  alias: Living room off at night
  trigger:
  - platform: time
    at: '21:30:00'
  action:
    service: light.turn_off
    entity_id: group.living_room
    data:
      transition: 60
- id: living_room_lights_morning
  alias: Living room on in morning
  trigger:
  - platform: time
    at: 05:00:00
  action:
    service: light.turn_on
    entity_id: group.living_room
    data:
      transition: 60
- id: living_room_lights_sunrise
  alias: Living room off after sunrise
  trigger:
  - platform: sun
    event: sunrise
    offset: 01:00:00
  action:
    service: light.turn_off
    entity_id: group.living_room
    data:
      transition: 60
