homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_lat
  longitude: !secret home_long
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 2
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Los_Angeles

# Enable full logging
logger:
  default: warning
  logs:
    homeassistant.components.mqtt: debug

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  api_password: !secret http_api_password
  base_url: !secret http_base_url

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Weather prediction
sensor:
  - platform: yr

# Text to speech
tts:
  - platform: google

zone:
  name: Home
  latitude: !secret home_lat
  longitude: !secret home_long
  radius: 50
  icon: mdi:home

zone 2:
  name: Work
  latitude: !secret work_lat
  longitude: !secret work_long
  radius: 150
  icon: mdi:worker

zone 3:
  name: Fruitvale BART
  latitude: 37.7758921
  longitude: -122.2240403
  radius: 150
  icon: mdi:train

group: !include groups.yaml
automation: !include automations.yaml

mqtt:
  broker: !secret mqtt_broker
  username: !secret mqtt_username
  password: !secret mqtt_password

device_tracker:
        #  - platform: nmap_tracker
        #    hosts: 10.0.1.1/24
        #    home_interval: 60
  - platform: owntracks
    max_gps_accuracy: 200

