# Core #########################################################################
homeassistant:
  name: Home
  latitude: !secret home_lat
  longitude: !secret home_long
  elevation: 2
  unit_system: imperial
  time_zone: America/Los_Angeles
  customize: !include includes/customize.yaml

logger:
  default: warning

frontend:

config:

http:
  api_password: !secret http_api_password
  base_url: !secret http_base_url

updater:

discovery:
  ignore:
    - netgear_router

conversation:

history:

logbook:

sun:

# Components ###################################################################

#tts:
#- platform: google

mqtt:
  broker: !secret mqtt_broker
  username: !secret mqtt_username
  password: !secret mqtt_password

# Includes #####################################################################

# Single files
device_tracker: !include includes/device_tracker.yaml
zone: !include includes/zone.yaml

# Merge List
automation: !include_dir_merge_list includes/automation
sensor: !include_dir_merge_list includes/sensor

# Merge Named
group: !include_dir_merge_named includes/group
