- platform: darksky
  api_key: !secret darksky_api
  monitored_conditions:
    - summary
    - apparent_temperature
    - temperature
    - temperature_max
    - temperature_min
    - precip_type
    - precip_intensity
    - precip_probability
